saida <- read.csv("teste_saida.txt",sep=",")

str(saida)
saida$X=NULL

#1- Estatísticas descritivas

sink("outpu9.txt")
print(names(saida))
print(summary(saida))
sink()


saida <- read.csv("teste_saida.txt",sep=",")
str(saida)


saida <- read.csv("teste_saida.txt",sep=",")
str(saida)


saida <- read.csv("teste_saida.txt",sep=",")
str(saida)

summary(saida)


saida <- read.csv("teste_saida.txt",sep=",")
str(saida)

summary(saida)

saida <- read.csv("teste_saida.txt",sep=",")




saida <- read.csv("teste_saida.txt",sep=",")
str(saida)

sink("output11.txt")
print(names(saida))
print(summary(saida))
sink()


saida <- read.csv("teste_saida.txt",sep=",")
str(saida)


saida <- read.csv("teste_saida.txt",sep=",")
str(saida)

sink("output10.txt")
print(names(saida))
print(summary(saida))
sink()


saida <- read.csv("teste_saida.txt",sep=",")
str(saida)


saida <- read.csv("teste_saida.txt",sep=",")
str(saida)


hist(saida$v0)

hist(saida$custoSim)
hist(saida$QProjNovos)
hist(saida$valorSim...custoSim)
hist(saida$QProj)

summary(saida)
summary(saida$VPLMnTotal)
hist(saida$TCongP)
hist(saida$QProjnDiv)


hist(saida$valorSim...custoSim)
hist(saida$v0)
hist(saida$custoSim)
hist(saida$valorSim)
hist(saida$QProj)
hist(saida$QProjNovos)
hist(saida$QProje)
hist(saida$Qproja)
hist(saida$Qprojae)
hist(saida$QProjDiv)
hist(saida$QProjDiva)
hist(saida$QProjDive)
hist(saida$QProjnDiv)
hist(saida$TCongP)
hist(saida$TCongReP)
hist(saida$NecRecP)
hist(saida$NecRecPa)
hist(saida$NecRecPe)
hist(saida$OrTotal)
hist(saida$QRecMax)
hist(saida$QModosP)
hist(saida$QProjCong)
hist(saida$QProjCongE)
hist(saida$QProjCongA)
hist(saida$RetMnTotalProj)
hist(saida$RetMxTotalProj)
hist(saida$RetMnTotalA)
hist(saida$RetMxTotalA)
hist(saida$DesemMxProj)
hist(saida$DesemMnProj)
hist(saida$VPLMnTotal)
hist(saida$VPLMxTotal)
hist(saida$CustoMnTotal)
hist(saida$CustoMxTotal)
hist(saida$VPLMnTotalA)
hist(saida$VPLMxTotalA)
hist(saida$VPLMnTotalE)
hist(saida$VPLMxTotalE)
hist(saida$CustoMnTotalCong)
hist(saida$CustoMxTotalCong)


sink("correlação.txt")
#print(names(saida))
print(cor(saida$v0,saida$valorSim...custoSim))
print(cor(saida$v0,saida$custoSim))
print(cor(saida$v0,saida$valorSim))
print(cor(saida$v0,saida$QProj))
print(cor(saida$v0,saida$QProjNovos))
print(cor(saida$v0,saida$QProje))
print(cor(saida$v0,saida$Qproja))
print(cor(saida$v0,saida$Qprojae))
print(cor(saida$v0,saida$QProjDiv))
print(cor(saida$v0,saida$QProjDiva))
print(cor(saida$v0,saida$QProjDive))
print(cor(saida$v0,saida$QProjnDiv))
print(cor(saida$v0,saida$TCongP))
print(cor(saida$v0,saida$TCongReP))
print(cor(saida$v0,saida$NecRecP))
print(cor(saida$v0,saida$NecRecPa))
print(cor(saida$v0,saida$NecRecPe))
print(cor(saida$v0,saida$OrTotal))
print(cor(saida$v0,saida$QRecMax))
print(cor(saida$v0,saida$QModosP))
print(cor(saida$v0,saida$QProjCong))
print(cor(saida$v0,saida$QProjCongE))
print(cor(saida$v0,saida$QProjCongA))
print(cor(saida$v0,saida$RetMnTotalProj))
print(cor(saida$v0,saida$RetMxTotalProj))
print(cor(saida$v0,saida$RetMnTotalA))
print(cor(saida$v0,saida$RetMxTotalA))
print(cor(saida$v0,saida$DesemMxProj))
print(cor(saida$v0,saida$DesemMnProj))
print(cor(saida$v0,saida$VPLMnTotal))
print(cor(saida$v0,saida$VPLMxTotal))
print(cor(saida$v0,saida$CustoMnTotal))
print(cor(saida$v0,saida$CustoMxTotal))
print(cor(saida$v0,saida$VPLMnTotalA))
print(cor(saida$v0,saida$VPLMxTotalA))
print(cor(saida$v0,saida$VPLMnTotalE))
print(cor(saida$v0,saida$VPLMxTotalE))
print(cor(saida$v0,saida$CustoMnTotalCong))
print(cor(saida$v0,saida$CustoMxTotalCong))
sink()


cor(saida$v0,saida$v0)
cor(saida$valorSim...custoSim,saida$custoSim)
cor(saida$valorSim...custoSim,saida$valorSim)
cor(saida$valorSim...custoSim,saida$RetMnTotalProj)
cor(saida$valorSim...custoSim,saida$OrTotal)
cor(saida$valorSim...custoSim,saida$DesemMxProj)


plot(saida$v0,saida$valorSim...custoSim)




plot(saida$v0,saida$valorSim...custoSim)
plot(saida$v0,saida$custoSim)
plot(saida$v0,saida$valorSim)
plot(saida$v0,saida$QProj)
plot(saida$v0,saida$QProjNovos)
plot(saida$v0,saida$QProje)
plot(saida$v0,saida$Qproja)
plot(saida$v0,saida$QProjDiv)
plot(saida$v0,saida$QProjDiva)
plot(saida$v0,saida$QProjDive)
plot(saida$v0,saida$QProjnDiv)
plot(saida$v0,saida$TCongP)
plot(saida$v0,saida$TCongReP)
plot(saida$v0,saida$NecRecP)
plot(saida$v0,saida$NecRecPa)
plot(saida$v0,saida$NecRecPe)
plot(saida$v0,saida$OrTotal)
plot(saida$v0,saida$QRecMax)
plot(saida$v0,saida$QProjCong)
plot(saida$v0,saida$QProjCongE)
plot(saida$v0,saida$QProjCongA)
plot(saida$v0,saida$RetMnTotalProj)
plot(saida$v0,saida$RetMxTotalProj)
plot(saida$v0,saida$RetMnTotalA)
plot(saida$v0,saida$RetMxTotalA)
plot(saida$v0,saida$DesemMxProj)
plot(saida$v0,saida$DesemMnProj)
plot(saida$v0,saida$VPLMnTotal)
plot(saida$v0,saida$VPLMxTotal)
plot(saida$v0,saida$CustoMnTotal)
plot(saida$v0,saida$CustoMxTotal)
plot(saida$v0,saida$VPLMnTotalA)
plot(saida$v0,saida$VPLMxTotalA)
plot(saida$v0,saida$VPLMnTotalE)
plot(saida$v0,saida$VPLMxTotalE)
plot(saida$v0,saida$CustoMnTotalCong)
plot(saida$v0,saida$CustoMxTotalCong)


corsaida = cor(saida[,c(2,10:15)])
sortedCor = mat.sort(corsaida)


library(psych)
library(ggplot2)
library(reshape2)
corsaida = cor(saida[,c(2,10:15)])
sortedCor = mat.sort(corsaida)
meltedCor = melt(sortedCor)
qplot(saida$v0, saida$QProj, data=meltedCor, fill=value, geom="tile")


sink("Regressão Linear e Linear Múltipla.txt")
lmv1 = lm(v0~valorSim...custoSim, data = saida)
print(summary(lmv1))
lmv2 = lm(v0~custoSim, data = saida)
print(summary(lmv2))
lmv3 = lm(v0~valorSim, data = saida)
print(summary(lmv3))
lmv4 = lm(v0~QProj, data = saida)
print(summary(lmv4))
lmv5 = lm(v0~QProjNovos, data = saida)
print(summary(lmv5))
lmv6 = lm(v0~QProje, data = saida)
print(summary(lmv6))
lmv7 = lm(v0~Qproja, data = saida)
print(summary(lmv7))
lmv8 = lm(v0~Qprojae, data = saida)
print(summary(lmv8))
lmv9 = lm(v0~QProjDiv, data = saida)
print(summary(lmv9))
lmv10 = lm(v0~QProjDiva, data = saida)
print(summary(lmv10))
lmv11 = lm(v0~QProjDive, data = saida)
print(summary(lmv11))
lmv12 = lm(v0~QProjnDiv, data = saida)
print(summary(lmv12))
lmv13 = lm(v0~TCongP, data = saida)
print(summary(lmv13))
lmv14 = lm(v0~TCongReP, data = saida)
print(summary(lmv14))
lmv15 = lm(v0~NecRecP, data = saida)
print(summary(lmv15))
lmv16 = lm(v0~NecRecPa, data = saida)
print(summary(lmv16))
lmv17 = lm(v0~NecRecPe, data = saida)
print(summary(lmv17))
lmv18 = lm(v0~OrTotal, data = saida)
print(summary(lmv18))
lmv19 = lm(v0~QRecMax, data = saida)
print(summary(lmv19))
lmv20 = lm(v0~QModosP, data = saida)
print(summary(lmv20))
lmv21 = lm(v0~QProjCong, data = saida)
print(summary(lmv21))
lmv22 = lm(v0~QProjCongE, data = saida)
print(summary(lmv22))
lmv23 = lm(v0~QProjCongA, data = saida)
print(summary(lmv23))
lmv24 = lm(v0~RetMnTotalProj, data = saida)
print(summary(lmv24))
lmv25 = lm(v0~RetMxTotalProj, data = saida)
print(summary(lmv25))
lmv26 = lm(v0~RetMnTotalA, data = saida)
print(summary(lmv26))
lmv27 = lm(v0~RetMxTotalA, data = saida)
print(summary(lmv27))
lmv28 = lm(v0~DesemMxProj, data = saida)
print(summary(lmv28))
lmv29 = lm(v0~DesemMnProj, data = saida)
print(summary(lmv29))
lmv30 = lm(v0~VPLMnTotal, data = saida)
print(summary(lmv30))
lmv31 = lm(v0~VPLMxTotal, data = saida)
print(summary(lmv31))
lmv32 = lm(v0~CustoMnTotal, data = saida)
print(summary(lmv32))
lmv33 = lm(v0~CustoMxTotal, data = saida)
print(summary(lmv33))
lmv34 = lm(v0~VPLMnTotalA, data = saida)
print(summary(lmv34))
lmv35 = lm(v0~VPLMxTotalA, data = saida)
print(summary(lmv35))
lmv36 = lm(v0~VPLMnTotalE, data = saida)
print(summary(lmv36))
lmv37 = lm(v0~VPLMxTotalE, data = saida)
print(summary(lmv37))
lmv38 = lm(v0~CustoMnTotalCong, data = saida)
print(summary(lmv38))
lmv39 = lm(v0~CustoMxTotalCong, data = saida)
print(summary(lmv39))
sink()


sink("correlação.txt")
#print(names(saida))
print(cor(saida$valorSim...custoSim,saida$v0))
print(cor(saida$valorSim...custoSim,saida$custoSim))
print(cor(saida$valorSim...custoSim,saida$valorSim))
print(cor(saida$valorSim...custoSim,saida$QProj))
print(cor(saida$valorSim...custoSim,saida$QProjNovos))
print(cor(saida$valorSim...custoSim,saida$QProje))
print(cor(saida$valorSim...custoSim,saida$Qproja))
print(cor(saida$valorSim...custoSim,saida$Qprojae))
print(cor(saida$valorSim...custoSim,saida$QProjDiv))
print(cor(saida$valorSim...custoSim,saida$QProjDiva))
print(cor(saida$valorSim...custoSim,saida$QProjDive))
print(cor(saida$valorSim...custoSim,saida$QProjnDiv))
print(cor(saida$valorSim...custoSim,saida$TCongP))
print(cor(saida$valorSim...custoSim,saida$TCongReP))
print(cor(saida$valorSim...custoSim,saida$NecRecP))
print(cor(saida$valorSim...custoSim,saida$NecRecPa))
print(cor(saida$valorSim...custoSim,saida$NecRecPe))
print(cor(saida$valorSim...custoSim,saida$OrTotal))
print(cor(saida$valorSim...custoSim,saida$QRecMax))
print(cor(saida$valorSim...custoSim,saida$QModosP))
print(cor(saida$valorSim...custoSim,saida$QProjCong))
print(cor(saida$valorSim...custoSim,saida$QProjCongE))
print(cor(saida$valorSim...custoSim,saida$QProjCongA))
print(cor(saida$valorSim...custoSim,saida$RetMnTotalProj))
print(cor(saida$valorSim...custoSim,saida$RetMxTotalProj))
print(cor(saida$valorSim...custoSim,saida$RetMnTotalA))
print(cor(saida$valorSim...custoSim,saida$RetMxTotalA))
print(cor(saida$valorSim...custoSim,saida$DesemMxProj))
print(cor(saida$valorSim...custoSim,saida$DesemMnProj))
print(cor(saida$valorSim...custoSim,saida$VPLMnTotal))
print(cor(saida$valorSim...custoSim,saida$VPLMxTotal))
print(cor(saida$valorSim...custoSim,saida$CustoMnTotal))
print(cor(saida$valorSim...custoSim,saida$CustoMxTotal))
print(cor(saida$valorSim...custoSim,saida$VPLMnTotalA))
print(cor(saida$valorSim...custoSim,saida$VPLMxTotalA))
print(cor(saida$valorSim...custoSim,saida$VPLMnTotalE))
print(cor(saida$valorSim...custoSim,saida$VPLMxTotalE))
print(cor(saida$valorSim...custoSim,saida$CustoMnTotalCong))
print(cor(saida$valorSim...custoSim,saida$CustoMxTotalCong))
sink()



saida <- read.csv("teste_saida.txt",sep=",")
str(saida)

sink("output11.txt")
#print(names(saida))
print(summary(saida))
sink()


saida <- read.csv("teste_saida.txt",sep=",")
str(saida)


sink("output11.txt")
#print(names(saida))
print(summary(saida))
sink()


saida <- read.csv("teste_saida.txt",sep=",")
str(saida)

sink("output11.txt")
#print(names(saida))
print(summary(saida))
sink()

saida <- read.csv("teste_saida.txt",sep=",")
str(saida)


sink("output11.txt")
#print(names(saida))
print(summary(saida))
sink()

saida <- read.csv("teste_saida.txt",sep=",")
str(saida)

sink("output11.txt")
#print(names(saida))
print(summary(saida))
sink()



saida <- read.csv("teste_saida.txt",sep=",")
str(saida)

sink("output11.txt")
#print(names(saida))
print(summary(saida))
sink()


saida <- read.csv("teste_saida.txt",sep=",")
str(saida)

sink("output11.txt")
#print(names(saida))
print(summary(saida))
sink()


saida <- read.csv("teste_saida.txt",sep=",")
str(saida)

sink("output11.txt")
#print(names(saida))
print(summary(saida))
sink()


sink("correlação.txt")
#print(names(saida))
print(cor(saida$valorSim...custoSim,saida$v0))
print(cor(saida$valorSim...custoSim,saida$custoSim))
print(cor(saida$valorSim...custoSim,saida$valorSim))
print(cor(saida$valorSim...custoSim,saida$QProj))
print(cor(saida$valorSim...custoSim,saida$QProjNovos))
print(cor(saida$valorSim...custoSim,saida$QProje))
print(cor(saida$valorSim...custoSim,saida$Qproja))
print(cor(saida$valorSim...custoSim,saida$Qprojae))
print(cor(saida$valorSim...custoSim,saida$QProjDiv))
print(cor(saida$valorSim...custoSim,saida$QProjDiva))
print(cor(saida$valorSim...custoSim,saida$QProjDive))
print(cor(saida$valorSim...custoSim,saida$QProjnDiv))
print(cor(saida$valorSim...custoSim,saida$TCongP))
print(cor(saida$valorSim...custoSim,saida$TCongReP))
print(cor(saida$valorSim...custoSim,saida$NecRecP))
print(cor(saida$valorSim...custoSim,saida$NecRecPa))
print(cor(saida$valorSim...custoSim,saida$NecRecPe))
print(cor(saida$valorSim...custoSim,saida$OrTotal))
print(cor(saida$valorSim...custoSim,saida$QRecMax))
print(cor(saida$valorSim...custoSim,saida$QProjCong))
print(cor(saida$valorSim...custoSim,saida$QProjCongE))
print(cor(saida$valorSim...custoSim,saida$QProjCongA))
print(cor(saida$valorSim...custoSim,saida$RetMnTotalProj))
print(cor(saida$valorSim...custoSim,saida$RetMxTotalProj))
print(cor(saida$valorSim...custoSim,saida$RetMnTotalA))
print(cor(saida$valorSim...custoSim,saida$RetMxTotalA))
print(cor(saida$valorSim...custoSim,saida$DesemMxProj))
print(cor(saida$valorSim...custoSim,saida$DesemMnProj))
print(cor(saida$valorSim...custoSim,saida$VPLMnTotal))
print(cor(saida$valorSim...custoSim,saida$VPLMxTotal))
print(cor(saida$valorSim...custoSim,saida$CustoMnTotal))
print(cor(saida$valorSim...custoSim,saida$CustoMxTotal))
print(cor(saida$valorSim...custoSim,saida$VPLMnTotalA))
print(cor(saida$valorSim...custoSim,saida$VPLMxTotalA))
print(cor(saida$valorSim...custoSim,saida$VPLMnTotalE))
print(cor(saida$valorSim...custoSim,saida$VPLMxTotalE))
print(cor(saida$valorSim...custoSim,saida$CustoMnTotalCong))
print(cor(saida$valorSim...custoSim,saida$CustoMxTotalCong))
sink()


saida <- read.csv("teste_saida.txt",sep=",")
str(saida)

sink("output11.txt")
#print(names(saida))
print(summary(saida))
sink()


sink("correlação.txt")
#print(names(saida))
print(cor(saida$valorSim...custoSim,saida$v0))
print(cor(saida$valorSim...custoSim,saida$custoSim))
print(cor(saida$valorSim...custoSim,saida$valorSim))
print(cor(saida$valorSim...custoSim,saida$QProj))
print(cor(saida$valorSim...custoSim,saida$QProjNovos))
print(cor(saida$valorSim...custoSim,saida$QProje))
print(cor(saida$valorSim...custoSim,saida$Qproja))
print(cor(saida$valorSim...custoSim,saida$QProjDiv))
print(cor(saida$valorSim...custoSim,saida$QProjDiva))
print(cor(saida$valorSim...custoSim,saida$QProjDive))
print(cor(saida$valorSim...custoSim,saida$QProjnDiv))
print(cor(saida$valorSim...custoSim,saida$TCongP))
print(cor(saida$valorSim...custoSim,saida$TCongReP))
print(cor(saida$valorSim...custoSim,saida$NecRecP))
print(cor(saida$valorSim...custoSim,saida$NecRecPa))
print(cor(saida$valorSim...custoSim,saida$NecRecPe))
print(cor(saida$valorSim...custoSim,saida$OrTotal))
print(cor(saida$valorSim...custoSim,saida$QRecMax))
print(cor(saida$valorSim...custoSim,saida$QProjCong))
print(cor(saida$valorSim...custoSim,saida$QProjCongE))
print(cor(saida$valorSim...custoSim,saida$QProjCongA))
print(cor(saida$valorSim...custoSim,saida$RetMnTotalProj))
print(cor(saida$valorSim...custoSim,saida$RetMxTotalProj))
print(cor(saida$valorSim...custoSim,saida$RetMnTotalA))
print(cor(saida$valorSim...custoSim,saida$RetMxTotalA))
print(cor(saida$valorSim...custoSim,saida$DesemMxProj))
print(cor(saida$valorSim...custoSim,saida$DesemMnProj))
print(cor(saida$valorSim...custoSim,saida$VPLMnTotal))
print(cor(saida$valorSim...custoSim,saida$VPLMxTotal))
print(cor(saida$valorSim...custoSim,saida$CustoMnTotal))
print(cor(saida$valorSim...custoSim,saida$CustoMxTotal))
print(cor(saida$valorSim...custoSim,saida$VPLMnTotalA))
print(cor(saida$valorSim...custoSim,saida$VPLMxTotalA))
print(cor(saida$valorSim...custoSim,saida$VPLMnTotalE))
print(cor(saida$valorSim...custoSim,saida$VPLMxTotalE))
print(cor(saida$valorSim...custoSim,saida$CustoMnTotalCong))
print(cor(saida$valorSim...custoSim,saida$CustoMxTotalCong))
sink()




hist(saida$valorSim...custoSim)
hist(saida$v0)
hist(saida$custoSim)
hist(saida$valorSim)
hist(saida$QProj)
hist(saida$QProjNovos)
hist(saida$QProje)
hist(saida$Qproja)
hist(saida$QProjDiv)
hist(saida$QProjDiva)
hist(saida$QProjDive)
hist(saida$QProjnDiv)
hist(saida$TCongP)
hist(saida$TCongReP)
hist(saida$NecRecP)
hist(saida$NecRecPa)
hist(saida$NecRecPe)
hist(saida$OrTotal)
hist(saida$QRecMax)
hist(saida$QProjCong)
hist(saida$QProjCongE)
hist(saida$QProjCongA)
hist(saida$RetMnTotalProj)
hist(saida$RetMxTotalProj)
hist(saida$RetMnTotalA)
hist(saida$RetMxTotalA)
hist(saida$DesemMxProj)
hist(saida$DesemMnProj)
hist(saida$VPLMnTotal)
hist(saida$VPLMxTotal)
hist(saida$CustoMnTotal)
hist(saida$CustoMxTotal)
hist(saida$VPLMnTotalA)
hist(saida$VPLMxTotalA)
hist(saida$VPLMnTotalE)
hist(saida$VPLMxTotalE)
hist(saida$CustoMnTotalCong)
hist(saida$CustoMxTotalCong)




sink("Regressão Linear e Linear Múltipla.txt")
lmv1 = lm(valorSim...custoSim~v0, data = saida)
print(summary(lmv1))
lmv2 = lm(valorSim...custoSim~custoSim, data = saida)
print(summary(lmv2))
lmv3 = lm(valorSim...custoSim~valorSim, data = saida)
print(summary(lmv3))
lmv4 = lm(valorSim...custoSim~QProj, data = saida)
print(summary(lmv4))
lmv5 = lm(valorSim...custoSim~QProjNovos, data = saida)
print(summary(lmv5))
lmv6 = lm(valorSim...custoSim~QProje, data = saida)
print(summary(lmv6))
lmv7 = lm(valorSim...custoSim~Qproja, data = saida)
print(summary(lmv7))
lmv9 = lm(valorSim...custoSim~QProjDiv, data = saida)
print(summary(lmv9))
lmv10 = lm(valorSim...custoSim~QProjDiva, data = saida)
print(summary(lmv10))
lmv11 = lm(valorSim...custoSim~QProjDive, data = saida)
print(summary(lmv11))
lmv12 = lm(valorSim...custoSim~QProjnDiv, data = saida)
print(summary(lmv12))
lmv13 = lm(valorSim...custoSim~TCongP, data = saida)
print(summary(lmv13))
lmv14 = lm(valorSim...custoSim~TCongReP, data = saida)
print(summary(lmv14))
lmv15 = lm(valorSim...custoSim~NecRecP, data = saida)
print(summary(lmv15))
lmv16 = lm(valorSim...custoSim~NecRecPa, data = saida)
print(summary(lmv16))
lmv17 = lm(valorSim...custoSim~NecRecPe, data = saida)
print(summary(lmv17))
lmv18 = lm(valorSim...custoSim~OrTotal, data = saida)
print(summary(lmv18))
lmv19 = lm(valorSim...custoSim~QRecMax, data = saida)
print(summary(lmv19))
lmv21 = lm(valorSim...custoSim~QProjCong, data = saida)
print(summary(lmv21))
lmv22 = lm(valorSim...custoSim~QProjCongE, data = saida)
print(summary(lmv22))
lmv23 = lm(valorSim...custoSim~QProjCongA, data = saida)
print(summary(lmv23))
lmv24 = lm(valorSim...custoSim~RetMnTotalProj, data = saida)
print(summary(lmv24))
lmv25 = lm(valorSim...custoSim~RetMxTotalProj, data = saida)
print(summary(lmv25))
lmv26 = lm(valorSim...custoSim~RetMnTotalA, data = saida)
print(summary(lmv26))
lmv27 = lm(valorSim...custoSim~RetMxTotalA, data = saida)
print(summary(lmv27))
lmv28 = lm(valorSim...custoSim~DesemMxProj, data = saida)
print(summary(lmv28))
lmv29 = lm(valorSim...custoSim~DesemMnProj, data = saida)
print(summary(lmv29))
lmv30 = lm(valorSim...custoSim~VPLMnTotal, data = saida)
print(summary(lmv30))
lmv31 = lm(valorSim...custoSim~VPLMxTotal, data = saida)
print(summary(lmv31))
lmv32 = lm(valorSim...custoSim~CustoMnTotal, data = saida)
print(summary(lmv32))
lmv33 = lm(valorSim...custoSim~CustoMxTotal, data = saida)
print(summary(lmv33))
lmv34 = lm(valorSim...custoSim~VPLMnTotalA, data = saida)
print(summary(lmv34))
lmv35 = lm(valorSim...custoSim~VPLMxTotalA, data = saida)
print(summary(lmv35))
lmv36 = lm(valorSim...custoSim~VPLMnTotalE, data = saida)
print(summary(lmv36))
lmv37 = lm(valorSim...custoSim~VPLMxTotalE, data = saida)
print(summary(lmv37))
lmv38 = lm(valorSim...custoSim~CustoMnTotalCong, data = saida)
print(summary(lmv38))
lmv39 = lm(valorSim...custoSim~CustoMxTotalCong, data = saida)
print(summary(lmv39))
sink()





install.packages("gplots")
install.packages("ggplot2")
library(psych)
library(ggplot2)
library(reshape2)
corsaida = cor(saida[c(1,35:38)])
sortedCor = mat.sort(corsaida)
meltedCor = melt(sortedCor)
qplot(x=Var1, y=Var2, data=meltedCor, fill=value, geom="tile")






#Teste
sink("Teste1.txt")
lmv1 = lm(valorSim...custoSim~QProj + QProjNovos + QProje + Qproja + QProjDiv + QProjDiva + QProjDive + QProjnDiv + TCongReP + NecRecP + NecRecPa + NecRecPe + OrTotal + QRecMax + QProjCong + QProjCongE + QProjCongA + RetMnTotalProj + RetMxTotalProj + RetMnTotalA + RetMxTotalA + DesemMxProj + VPLMnTotal + VPLMxTotal + CustoMnTotal + CustoMxTotal + VPLMnTotalA + VPLMxTotalA + VPLMnTotalE + VPLMxTotalE + CustoMnTotalCong + CustoMxTotalCong, data = saida)
print(summary(lmv1))
sink()